options(repos = c(CRAN = "http://cran.rstudio.com"))
#install.packages('Seurat')
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE)
devtools::install_github("mojaveazure/seurat-disk")
devtools::install_github("immunogenomics/harmony")
devtools::install_github("renozao/NMF@devel")
devtools::install_github("jokergoo/circlize")
devtools::install_github("jokergoo/ComplexHeatmap")
devtools::install_github("sqjin/CellChat")

